version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Run app
          command: docker-compose up -d --build

workflows:
  main:
    jobs:
      - build
