version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run app
          command: docker-compose up -d --build

workflows:
  main:
    jobs:
      - build
